language: python
python:
  - "3.6"
before_install:
  - sudo apt-get -y install unixodbc-dev
jobs:
  include:
    - name: "Unit tests"
      script: pytest -v
    - name: "Coverage"
      script: pytest --cov=. --cov-fail-under=100
    - name: "Linting"
      script: ./check_formatting.sh
