language: python
python:
  - "3.5"
jobs:
  include:
    - name: "Unit tests"
      script: pytest -v
    - name: "Coverage"
      script: pytest --cov=. --cov-fail-under=100
    - name: "Linting"
      script: ./check_formatting.sh
