name: Update python dependencies

on:
  workflow_dispatch:
  schedule:
    - cron:  "5 4 * * WED"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: "opensafely-core/setup-action@v1"
      with:
        python-version: "3.12"
        install-just: true

    - uses: actions/create-github-app-token@v1
      id: generate-token
      with:
        app-id: ${{ vars.CREATE_PR_APP_ID }}
        private-key: ${{ secrets.CREATE_PR_APP_PRIVATE_KEY }}

    - uses: bennettoxford/update-dependencies-action@v1
      id: update
      with:
        token: ${{ steps.generate-token.outputs.token }}
        pr_title: "Update python dependencies"

    - name: Notify slack of PR
      if: ${{ steps.update.outputs.pull-request-operation != 'none' }}
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ secrets.BENNETTBOT_SLACK_BOT_TOKEN }}
        payload: |
          channel: "C080S7W2ZPX"
          text: "Update dependencies\n${{ steps.update.outputs.pull-request-url }}"
